spring:
  application:
    name: geolocalizacao

app:
  mqtt:
    host: tcp://localhost:1883
    client-id: spring-mqtt-client-${random.uuid}
    producerTopic: tp/producer/customer/geolocalizacao

#logging:
#  level:
#    org.springframework.integration.mqtt: DEBUG
#    org.eclipse.paho.client.mqttv3: DEBUG